import { FoodLog } from "../types/models";

export const testFoodLogs: Omit<FoodLog, "id" | "logDate" | "createdAt">[] = [
  {
    title: "🍓 Greek Yogurt",
    description: "Plain Greek yogurt topped with berries and honey",
    foodComponents: [
      { amount: 200, name: "Greek yogurt", unit: "g" },
      { amount: 60, name: "Mixed berries", unit: "g" },
      { amount: 15, name: "Honey", unit: "ml" },
    ],
    calories: 220,
    protein: 18,
    carbs: 28,
    fat: 5,
    isEstimating: false,
  },
  {
    title: "🥑 Avocado Toast",
    description: "Whole grain toast with mashed avocado and olive oil",
    foodComponents: [
      {
        amount: 2,
        name: "Whole grain bread slice",
        unit: "piece",
        recommendedMeasurement: { amount: 70, unit: "g" },
      },
      { amount: 90, name: "Mashed avocado", unit: "g" },
      { amount: 10, name: "Olive oil", unit: "ml" },
    ],
    calories: 340,
    protein: 8,
    carbs: 32,
    fat: 22,
    isEstimating: false,
  },
  {
    title: "🥪 Turkey Sandwich",
    description: "Turkey breast with crisp veggies on whole wheat bread",
    foodComponents: [
      {
        amount: 2,
        name: "Whole wheat bread slice",
        unit: "piece",
        recommendedMeasurement: { amount: 80, unit: "g" },
      },
      { amount: 120, name: "Turkey breast", unit: "g" },
      { amount: 40, name: "Tomato slices", unit: "g" },
      { amount: 30, name: "Lettuce", unit: "g" },
      { amount: 15, name: "Mustard", unit: "ml" },
    ],
    calories: 410,
    protein: 32,
    carbs: 42,
    fat: 12,
    isEstimating: false,
  },
  {
    title: "🥗 Quinoa Veggie Bowl",
    description: "Quinoa with roasted vegetables, chickpeas, and tahini",
    foodComponents: [
      { amount: 180, name: "Cooked quinoa", unit: "g" },
      { amount: 120, name: "Roasted vegetables", unit: "g" },
      { amount: 40, name: "Chickpeas", unit: "g" },
      { amount: 20, name: "Lemon tahini dressing", unit: "ml" },
    ],
    calories: 520,
    protein: 18,
    carbs: 64,
    fat: 20,
    isEstimating: false,
  },
  {
    title: "🍜 Chicken Stir Fry",
    description: "Grilled chicken with vegetables and brown rice",
    foodComponents: [
      { amount: 180, name: "Grilled chicken breast", unit: "g" },
      { amount: 150, name: "Stir-fried vegetables", unit: "g" },
      { amount: 150, name: "Cooked brown rice", unit: "g" },
      { amount: 15, name: "Soy sauce", unit: "ml" },
    ],
    calories: 620,
    protein: 48,
    carbs: 62,
    fat: 18,
    isEstimating: false,
  },
  {
    title: "🐟 Salmon Plate",
    description: "Baked salmon with rice and asparagus",
    foodComponents: [
      { amount: 150, name: "Baked salmon", unit: "g" },
      { amount: 160, name: "Steamed jasmine rice", unit: "g" },
      { amount: 80, name: "Roasted asparagus", unit: "g" },
      { amount: 5, name: "Olive oil", unit: "ml" },
    ],
    calories: 540,
    protein: 38,
    carbs: 45,
    fat: 22,
    isEstimating: false,
  },
  {
    title: "🥣 Overnight Oats",
    description: "Oats soaked in almond milk with chia seeds and berries",
    foodComponents: [
      { amount: 60, name: "Rolled oats", unit: "g" },
      { amount: 200, name: "Almond milk", unit: "ml" },
      { amount: 20, name: "Chia seeds", unit: "g" },
      { amount: 50, name: "Blueberries", unit: "g" },
    ],
    calories: 380,
    protein: 12,
    carbs: 52,
    fat: 12,
    isEstimating: false,
  },
  {
    title: "🥤 Protein Shake",
    description: "Chocolate protein blended with milk and banana",
    foodComponents: [
      { amount: 30, name: "Chocolate protein powder", unit: "g" },
      { amount: 250, name: "Milk", unit: "ml" },
      {
        amount: 1,
        name: "Banana",
        unit: "piece",
        recommendedMeasurement: { amount: 120, unit: "g" },
      },
    ],
    calories: 320,
    protein: 32,
    carbs: 35,
    fat: 8,
    isEstimating: false,
  },
  {
    title: "🥕 Hummus Plate",
    description: "Hummus served with carrot and cucumber sticks",
    foodComponents: [
      { amount: 80, name: "Hummus", unit: "g" },
      { amount: 120, name: "Carrot sticks", unit: "g" },
      { amount: 100, name: "Cucumber sticks", unit: "g" },
      { amount: 6, name: "Olive oil", unit: "ml" },
    ],
    calories: 310,
    protein: 11,
    carbs: 28,
    fat: 18,
    isEstimating: false,
  },
  {
    title: "🍝 Beef Bolognese",
    description: "Spaghetti with beef bolognese and parmesan",
    foodComponents: [
      { amount: 200, name: "Cooked spaghetti", unit: "g" },
      { amount: 140, name: "Beef bolognese sauce", unit: "g" },
      { amount: 20, name: "Parmesan cheese", unit: "g" },
    ],
    calories: 680,
    protein: 32,
    carbs: 78,
    fat: 26,
    isEstimating: false,
  },
  {
    title: "🍣 Salmon Nigiri",
    description: "Salmon nigiri pieces with soy sauce",
    foodComponents: [
      {
        amount: 8,
        name: "Salmon nigiri",
        unit: "piece",
        recommendedMeasurement: { amount: 360, unit: "g" },
      },
      { amount: 10, name: "Soy sauce", unit: "ml" },
    ],
    calories: 520,
    protein: 28,
    carbs: 78,
    fat: 12,
    isEstimating: false,
  },
  {
    title: "🍇 Fruit Plate",
    description: "Seasonal fruit selection",
    foodComponents: [
      {
        amount: 1,
        name: "Apple",
        unit: "piece",
        recommendedMeasurement: { amount: 180, unit: "g" },
      },
      {
        amount: 1,
        name: "Orange",
        unit: "piece",
        recommendedMeasurement: { amount: 160, unit: "g" },
      },
      { amount: 120, name: "Grapes", unit: "g" },
    ],
    calories: 240,
    protein: 3,
    carbs: 62,
    fat: 1,
    isEstimating: false,
  },
];
